---
# handlers file for common
- name: restart nfs
  ansible.builtin.service:
    name: nfs-server
    state: restarted
- name: dnf makecache
  ansible.builtin.command: "dnf makecache --refresh"
- name: restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted