- name: Create networkmanager interface
  community.general.nmcli:
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    ip4: "{{ item.ip4 }}" if item.ip4 is defined else null
    gw4: "{{ item.gw4 }}" if item.gw4 is defined else null
    dns4: "{{ item.dns4 }}" if item.dns4 is defined else null
    dns4_search: "{{ item.dns4_search }}" if item.dns4_search is defined else null
    method6: "{{ item.method4 }}" if item.method4 is defined else null
    master: "{{ item.master }}" if item.master is defined else null
    state: "{{ item.state }}" if item.state is defined else "present"
    type: "{{ item.type }}" if item.type is defined else "ethernet"
    ip6: "{{ item.ip6 }}" if item.ip6 is defined else null
    gw6: "{{ item.gw6 }}" if item.gw6 is defined else null
    dns6: "{{ item.dns6 }}" if item.dns6 is defined else null
    dns6_search: "{{ item.dns6_search }}" if item.dns6_search is defined else null
    method6: "{{ item.method6 }}" if item.method6 is defined else null
    hairpin: "{{ item.hairpin }}" if item.hairpin is defined else null
    mtu: "{{ item.mtu }}" if item.mtu is defined else null
  with_items: "{{ ethernet }}"
  when: ethernet is defined

- name: Overlay Module
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Create kube-deps.conf
  ansible.builtin.copy:
    content: "overlay\nbr_netfilter"
    dest: /etc/modules-load.d/kube-deps.conf

- name: IP Forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Disable Return Path Filtering
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
  with_items:
    - net.ipv4.conf.default.rp_filter
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.lo.rp_filter

- name: Enable Firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Common Firewall Ports Enabled
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ common_ports }}"

- name: Disable NetworkManager control of DNS
  ansible.builtin.template:
    src: 90-disable-nm-dns.conf.j2
    dest: /etc/NetworkManager/conf.d/90-disable-nm-dns.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart NetworkManager

- name: Enable nameservers
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  when: dns is defined and dns.nameservers is defined

- name: Enable hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: dns is defined and dns.hosts is defined
