- name: Create networkmanager interface
  community.general.nmcli:
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    ip4: "{{ item.ip4 | default(omit) }}"
    gw4: "{{ item.gw4 | default(omit) }}"
    dns4: "{{ item.dns4 | default(omit) }}"
    dns4_search: "{{ item.dns4_search | default(omit) }}"
    method6: "{{ item.method4 | default(omit) }}"
    master: "{{ item.master  | default(omit) }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
    type: "{{ item.type if item.type is defined else 'ethernet' }}"
    ip6: "{{ item.ip6 | default(omit) }}"
    gw6: "{{ item.gw6 | default(omit) }}"
    dns6: "{{ item.dns6 | default(omit) }}"
    dns6_search: "{{ item.dns6_search | default(omit) }}"
    method6: "{{ item.method6 | default(omit) }}"
    hairpin: "{{ item.hairpin | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
  with_items: "{{ ethernet }}"
  when: ethernet is defined

- name: Overlay Module
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Create kube-deps.conf
  ansible.builtin.copy:
    content: "overlay\nbr_netfilter"
    dest: /etc/modules-load.d/kube-deps.conf

- name: IP Forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Disable Return Path Filtering
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
  with_items:
    - net.ipv4.conf.default.rp_filter
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.lo.rp_filter

- name: Enable Firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  when: firewall_enabled

- name: Disable Firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
  when: not firewall_enabled

- name: Common Firewall Ports Enabled
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ common_ports }}"
  when: firewall_enabled

- name: NFS Firewall Ports Enabled
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ nfs_ports }}"
  when: firewall_enabled and exports | default([]) != []

- name: Disable NetworkManager control of DNS
  ansible.builtin.template:
    src: 90-disable-nm-dns.conf.j2
    dest: /etc/NetworkManager/conf.d/90-disable-nm-dns.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart NetworkManager

- name: Enable nameservers
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  when: dns is defined and dns.nameservers is defined

- name: Enable hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: dns is defined and dns.hosts is defined
