---
- name: cuda-rhel9 Repo setup
  ansible.builtin.yum_repository:
    name: cuda-rhel9
    description: cuda dependencies which are needed for nvidia drivers
    baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64
    gpgcheck: true
    gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/D42D0685.pub

- name: Install the nvidia-driver-cuda package
  ansible.builtin.dnf:
    name: '@Development tools'
    state: present

- name: libnvidia-container Repo setup
  ansible.builtin.yum_repository:
    name: libnvidia-container
    description: nvidia-container dependencies which are needed for passing gpu through CRI
    baseurl: https://nvidia.github.io/libnvidia-container/stable/centos7/$basearch
    gpgcheck: true
    gpgkey: https://nvidia.github.io/libnvidia-container/gpgkey

- name: Install nvidia-container-toolkit
  ansible.builtin.dnf:
    name: nvidia-container-toolkit
    state: present
