- name: Create kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: kubeadm_join_command
  changed_when: kubeadm_join_command.rc == 0
  failed_when: kubeadm_join_command.rc != 0