---
- name: Create kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: kubeadm_join_command
  changed_when: kubeadm_join_command.rc == 0
  failed_when: kubeadm_join_command.rc != 0
  delegate_to: "{{ groups['control_plane'][0] }}"
- name: Create fact for kubeadm join command
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ kubeadm_join_command.stdout }}"
  when: kubeadm_join_command is defined
- name: Create kubeadm join command for control plane
  ansible.builtin.shell: echo $(kubeadm token create --print-join-command) --control-plane --certificate-key $(kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace)
  register: kubeadm_join_command_control_plane
  changed_when: kubeadm_join_command_control_plane.rc == 0
  failed_when: kubeadm_join_command_control_plane.rc != 0
  delegate_to: "{{ groups['control_plane'][0] }}"
- name: Create fact for kubeadm join command for control plane
  ansible.builtin.set_fact:
    kubeadm_join_command_control_plane: "{{ kubeadm_join_command_control_plane.stdout }}"
  when: kubeadm_join_command_control_plane is defined