---
- name: Install HAProxy
  package:
    name: haproxy
    state: present

- name: Create HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/conf.d/kube-apiserver.cfg
    mode: 0644
  notify:
    - restart haproxy
    
- name: Enable and start HAProxy service
  systemd:
    name: haproxy
    state: started
    enabled: yes