---
- name: Create kubeadm.yaml in /root/ for kubeadm init
  ansible.builtin.template:
    src: kubeadm.yaml.j2
    dest: /root/kubeadm.yaml
    owner: root
    group: root
    mode: '0600'

- name: Check if kubernetes is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_installed

- name: Initialize Kubernetes Cluster
  ansible.builtin.shell: kubeadm init --upload-certs --config /root/kubeadm.yaml
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  changed_when: kubeadm_init.rc == 0
  failed_when: kubeadm_init.rc != 0
  notify: restart kubelet
  when: kubernetes_installed.stat is not defined or kubernetes_installed.stat.exists == false

- name: Make /etc/kubernetes/admin.conf readable by wheel group
  ansible.builtin.file:
    path: /etc/kubernetes/admin.conf
    owner: root
    group: wheel
    mode: '0640'
  when: kubernetes_installed.stat.exists == true or kubeadm_init.rc == 0
