- name: Create kubeadm.yaml in /root/ for kubeadm init
  ansible.builtin.template:
    src: kubeadm.yaml.j2
    dest: /root/kubeadm.yaml
    owner: root
    group: root
    mode: '0600'

- name: Initialize Kubernetes Cluster
  ansible.builtin.shell: kubeadm init --config /root/kubeadm.yaml
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  changed_when: kubeadm_init.rc == 0
  failed_when: kubeadm_init.rc != 0
  notify: restart kubelet