# Check if node is already joined to the cluster

- name: Label nodes as downloader if they are in the downloader group
  ansible.builtin.shell: "kubectl --kubeconfig /etc/kubernetes/admin.conf label nodes {{ inventory_hostname }} {{ item }}=yes"
  when: inventory_hostname in groups[item]
  with_items: "{{ groups.keys() }}"
  delegate_to: "{{ groups['control_plane'][0] }}"
