---
- name: If Firewall Is Enabled
  when: firewall_enabled
  block:
  - name: Kubernetes Firewall Ports Enabled
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    with_items: "{{ kube_ports }}"
  - name: Add pod cidr to trusted zone
    ansible.posix.firewalld:
      zone: trusted
      source: "{{ kube_pod_cidr }}"
      source: "{{ kube_service_cidr }}"
      state: enabled
      permanent: yes
  - name: Add forward to public zone
    ansible.builtin.command:
      cmd: firewall-cmd --permanent --zone=trusted --add-forward
