---
- hosts: "{{ groups['control_plane'][0] }}"
  become: true
  become_method: sudo
  become_user: root
  roles:
    - kube
  vars:
    action: create_join_command

- hosts: "{{ groups['control_plane'][1:] }}"
  become: true
  become_method: sudo
  become_user: root
  roles:
    - kube
  vars:
    action: join