---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  roles:
    - kube
  vars:
    action: create_join_command

- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  roles:
    - kube
  vars:
    action: join