---
# defaults file for kube
kube_packages:
  - containerd.io
  - "kubeadm-{{ kube.version }}"
  - "kubectl-{{ kube.version }}"
  - "kubelet-{{ kube.version }}"
kube_ports:
  - 6443/tcp # kube-apiserver
  - 4240/tcp # cilum-health
  - 8472/udp # cilum-vxlan
  - 2379-2380/tcp # kube-etcd
  - 10250-10252/tcp # kubelet
haproxy_frontend_ip: 127.0.0.1
haproxy_frontend_port: 8443
control_plane_port: 6443