---
# defaults file for kube
kube_dns_domain: cluster.local
kube_packages:
  - containerd.io
  - "kubeadm-{{ kube.version }}"
  - "kubectl-{{ kube.version }}"
  - "kubelet-{{ kube.version }}"
kube_ports:
  - 6443/tcp # kube-apiserver
  - 4240/tcp # cilum-health
  - 8472/udp # cilum-vxlan
  - 2379-2380/tcp # kube-etcd
  - 10250-10252/tcp # kubelet
kube_pod_cidr: 172.16.0.0/12
kube_service_cidr: 192.168.0.0/16
haproxy_frontend_ip: 127.0.0.1
haproxy_frontend_port: 8443
control_plane_port: 6443
timoni_bin_url: https://github.com/stefanprodan/timoni/releases/download/v0.20.0/timoni_0.20.0_linux_amd64.tar.gz
